function lines = read_clpsecm_data(dataProfile)

%-Read xls file
folderpwd = 'data/';
filename = ['clpsecm_',dataProfile.date,...
            '_S',      num2str(dataProfile.sample_number,'%03d'),...
            '_L',      num2str(dataProfile.nlines,'%02d'),...
            '_',       num2str(dataProfile.version,'%02d'),...
            '.xlsx'];
m = (dataProfile.scan_length) / (dataProfile.scan_resolution);
s = (dataProfile.scan_start_location) /  (dataProfile.scan_resolution);

%-Assign lines data
lines = ScanLines(dataProfile.angles);
lines.nmeasures = m;
lines.xticks = xlsread([folderpwd,filename] ,2 ,...
               ['B',num2str(s+2),':B',num2str(s+m+1)]);                
for L = 1:dataProfile.nlines
    lines.currents(:,L) = ...
        xlsread([folderpwd,filename] ,L+1 ,...
        ['C', num2str(s+2),':C',num2str(s+m+1)]);  
end

